spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vk
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update),production set to none or comment it
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

spring-doc:
  api-docs:
    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html  # Путь к странице Swagger UI

server:
  port: 8080

#logging:
#  config: classpath:log4j2-plain.xml
